name: shimysqldemo
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  mysql1: ^0.17.1
  http: "0.11.3+17"
  dio: ^3.0.5
  flutter:
    sdk: flutter

  
  cupertino_icons: ^0.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/shilogo1.png
    - assets/userb.png
  